### ISSUE TITLE
NoneType

### ISSUE THREAD

**Issue by jwschmo** [openxc/openxc-python#81]
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/openxc/sources/base.py", line 195, in run
  File "/usr/local/lib/python2.7/dist-packages/openxc/sources/usb.py", line 72, in read
  File "/usr/local/lib/python2.7/dist-packages/openxc/sources/usb.py", line 88, in _read
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'core'

**Comment by emarsman** [comment]
Can you please provide more info on how this error is generated and steps to reproduce it?

**Comment by theJalden** [comment]
I've been getting the same issue.  I'm running Debian with a low horse power system.  Got ~248 MB of memory.

Just for the record, the results of the "Free command"

> root@OpenXC-VI-V2X-F1A4:~# free -m
>              total       used       free     shared    buffers     cached
> Mem:           248         66        182          0          8         33
> -/+ buffers/cache:         23        224

I regularily get errors when executing the "openxc-control version", and "openxc-control id".

The full Errors are:

> root@OpenXC-VI-V2X-F1A4:~# openxc-control id
> Device ID is 0006666D53F4
> Exception in thread Thread-1 (most likely raised during interpreter shutdown):
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
>   File "/usr/local/lib/python2.7/dist-packages/openxc-0.12.0-py2.7.egg/openxc/sources/base.py", line 196, in run
>   File "/usr/local/lib/python2.7/dist-packages/openxc-0.12.0-py2.7.egg/openxc/sources/usb.py", line 72, in read
>   File "/usr/local/lib/python2.7/dist-packages/openxc-0.12.0-py2.7.egg/openxc/sources/usb.py", line 88, in _read
> <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'USBError'

> root@OpenXC-VI-V2X-F1A4:~# openxc-control version
> Device is running version 7.1.1 (default)
> Exception in thread Thread-1 (most likely raised during interpreter shutdown):
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
>   File "/usr/local/lib/python2.7/dist-packages/openxc-0.12.0-py2.7.egg/openxc/sources/base.py", line 214, in run
>   File "/usr/local/lib/python2.7/dist-packages/openxc-0.12.0-py2.7.egg/openxc/formats/json.py", line 19, in parse_next_message
>   File "/usr/local/lib/python2.7/dist-packages/openxc-0.12.0-py2.7.egg/openxc/formats/json.py", line 35, in deserialize
>   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
> <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'utf_8_decode'

In both cases the interpreter doesn't seem to recognize an imported module, this may be due to limited hardware, I can't replicate this issue when running from a PC.

**Comment by scarabdesign** [comment]
I'm also seeing these errors about 50% to 70% of the time. What's more, it sometimes only shows the first few lines of the exception before spitting me out to the shell. 
```
dev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_innerdev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
Exception in thread Thread-1 (most likely raised during interpreter shutdown):dev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
dev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/openxc/sources/base.py", line 195, in run
  File "/usr/local/lib/python2.7/dist-packages/openxc/sources/usb.py", line 72, in read
  File "/usr/local/lib/python2.7/dist-packages/openxc/sources/usb.py", line 88, in _read
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'USBError'dev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
Exception in thread Thread-1 (most likely raised during interpreter shutdown):dev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
Exception in thread Thread-1 (most likely raised during interpreter shutdown):dev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
Exception in thread Thread-1 (most likely raised during interpreter shutdown):dev@nuc:~$ sudo openxc-control id
Device ID is FF:FF:FF:FF:FF:FF
dev@nuc:~$ 
```
From what I'm gathering, this seems to be the result of threads not exiting cleanly. I can't say why this would be different between platforms (it strikes me as funny that there are so few Linux OpenXC tinkerers), but `Exception in thread Thread-1 (most likely raised during interpreter shutdown)` is a clue. The final error at the end comes when the object being requested is no longer in memory. In both the "id" and "version" cases, it does successfully return the desired values (if I am to believe that my device id "FF:FF:FF:FF:FF:FF", but @theJalden looks to be getting a valid id).

For instance, "/usr/local/lib/python2.7/dist-packages/openxc-0.12.0-py2.7.egg/openxc/sources/usb.py", line 88 is the catching of an exception, but at this point, it seams, usb.core is turned into nothing (probably unloaded because the thread was told to exit).

The first [google result](http://stackoverflow.com/questions/20596918/python-exception-in-thread-thread-1-most-likely-raised-during-interpreter-shutd) for the "Exception in thread" line suggests this is improper use of the daemon threads, but I don't have enough info or knowledge to corroborate or contradict that claim. Anyway, I'll keep poking at it and come back with further info if I glean anything.

**Comment by emarsman** [comment]
FYI, the MAC showing as all FF:FF was a bug. It is fixed in current vi-firmware master (this PR: https://github.com/openxc/vi-firmware/pull/361). Not in the pre-compiled ones yet though. Working on a few other things before release.

**Comment by kylewludwig** [comment]
Additionally `openxc-control version` from terminal gave an error but still read out the version while I had the OpenXC Enabler open on an Android phone.

```
Can't read logs from data source -- stopping: ("USB device couldn't be read", USBError(60, 'Operation timed out'))
Device is running version 7.1.1 (default)
```

However, when I locked the screen on the phone with OpenXC Enabler still running there were additional errors reported:
```
Can't read logs from data source -- stopping: ("USB device couldn't be read", USBError(60, 'Operation timed out'))
Device is running version 7.1.1 (default)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/Users/kylewludwig/openxc-python/openxc/sources/base.py", line 213, in run
  File "/Users/kylewludwig/openxc-python/openxc/formats/json.py", line 19, in parse_next_message
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'deserialize'
```

Here's the screenshot (same info):
![image](https://cloud.githubusercontent.com/assets/24880524/26326310/776252c6-3eef-11e7-877c-de6435bf17d9.png)

**Comment by raphaottoni** [comment]
I have the exact same problem as @kylewludwig.  Did you manage to solve it? 

Every command I sent, I do get the answer, but also a "Can't read logs from data source -- stopping: ("USB device couldn't be read", USBError(60, 'Operation timed out'))"

<img width="1680" alt="screen shot 2017-07-14 at 4 24 45 pm" src="https://user-images.githubusercontent.com/5016450/28227600-0fa7795e-68b1-11e7-8559-0d67c30bd8b0.png">
<img width="1023" alt="screen shot 2017-07-14 at 4 25 04 pm" src="https://user-images.githubusercontent.com/5016450/28227601-0faf39b4-68b1-11e7-9a04-22c240b6410b.png">

I am also using a Mac and mine is with Sierra Version 10.12
