### ISSUE TITLE
requests==2.4.1 error for generate-firmware in vagrant env

### ISSUE THREAD

**Issue by emarsman** [openxc/openxc-python#97]
When using % openxc-generate-firmware-code in the current vi-firmware vagrant environment, you get an error:

`
Traceback (most recent call last):
  File "/usr/local/bin/openxc-generate-firmware-code", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests==2.4.1
`

However, pip list shows the correct version (requests (2.4.1)). 

Temporary workaround is to run the following command: 

% sudo pip install --upgrade setuptools

This upgrades setuptools from 0.6rc11 to 36.4.0, but doesn't change the 'requests' version. Could be a bad error message.

**Comment by pjt0620** [comment]
Fixed in  #107
